### ISSUE TITLE
Placement images à automatiser

### ISSUE THREAD

**Issue by gbert1** [dvoitsek/recolnat-lab#1]
Le placement des images du set exemple est actuellement manuel, il faut qu'il soit automatique.

**Comment by gbert1** [comment]
En ligne 5 par 5.
5 sur la première, puis 5 sur la deuxième, etc.
Le nb 5 est arbitraire. 
Soit tu es capable de le calculer pour inscrire le nb total d'image ds un rectangle de rapport 4/3.
Soit on le rend paramétrable qq part.
Soit on le fixe ds un premier tps arbitrairement à 5.

**Comment by dvoitsek** [comment]
Le set exemple sera pré-placé. Pour le placement automatique en matrice on verra plus tard.

**Comment by gbert1** [comment]
Il me semblait que tu m'avais montré un placement en ligne qui fonctionnait bien.
Contentons-nous en pour l'instant. C'est déjà une première excellente solution (peut-être même suffisante à terme).
Peux-tu nous la proposer dans la VM ?

**Comment by dvoitsek** [comment]
C'est déjà dans la Vm. Au lieu de tirer l'image pour la placer, clique sur un des deux boutons en-dessous.

**Comment by gbert1** [comment]
Automatiser complètement et supprimer tous ces choix. 
L'utilisateur a déjà dû cliquer de nombreuses fois dans Explore, puis dans le gestionnaire de sets.

**Comment by dvoitsek** [comment]
Option de placement en matrice implémentée en dev.
