### ISSUE TITLE
Poignées illisibles (déplacement et retaillage)

### ISSUE THREAD

**Issue by gbert1** [dvoitsek/recolnat-lab#10]
Les 2 poignées ne sont pas compréhensibles ergonomiquement.
Il faut trouver une solution.
En bas, il faut une double flèche orientée nord-ouest / sud-est
En haut, il faut une main.
Et que ces 2 symboles, soient visibles qq soit le zoom.

Que peux-tu proposer techniquement ?

**Comment by dvoitsek** [comment]
Je peux proposer de remplacer les affichages actuels par les deux icônes proposées.

**Comment by gbert1** [comment]
Quid de leur taille ? C'est le véritable pb pour Manuel comme pour moi.
La plupart du temps, ils st minuscules.
De toute façon, ils devraient être de la taille de la barre.
Pourrais-tu tracer des lignes ? Si oui, on peut trouver une solution basée sur des lignes.

**Comment by dvoitsek** [comment]
Ils sont toujours de taille constante (5px) quel que soit le zoom. Est-ce que 10px seraient suffisants ?

Par contre s'il faut qu'ils soient de la taille de la barre ils ne seront pas de la même taille quel que soit le zoom.

De quel tracé de lignes avez-vous besoin ?

**Comment by gbert1** [comment]
Nous en discuterons de vive voix autour du paper board.

**Comment by dvoitsek** [comment]
Voici une version avec des poignées de 20px. Une opinion ?
![handles](https://cloud.githubusercontent.com/assets/8166976/16043916/61b2123c-3242-11e6-9900-6ee31a46b9b9.png)

**Comment by gbert1** [comment]
Je n'aime pas :-(
Voici en PJ une solution à base de 3 lignes obliques pour le coin bas droit : 
![capture d ecran 2016-06-14 22 02 39](https://cloud.githubusercontent.com/assets/19670563/16057796/ea4a1f66-327b-11e6-9a40-611712dca9e0.png)

**Comment by dvoitsek** [comment]
Implémenté en dev et déployé en test et Vm.

**Comment by gbert1** [comment]
Je l'ai vue, oui. Par contre, elle disparaît qd on zoome en agrandissant.
