### ISSUE TITLE
pp : mention "Chemin : "

### ISSUE THREAD

**Issue by gbert1** [dvoitsek/recolnat-lab#101]
Qd je clique sur un segment rouge longueur sur la paillasse, pp affiche 

Chemin : étiq
Création : 06/10/2016 à 14:50:56
Longueur = 102.92 mm

Il faut seulement selon notre discussion de lundi afficher : 

**étiq**
Création : 06/10/2016 à 14:50:56
Longueur = 102.92 mm

**Comment by dvoitsek** [comment]
Ok, le type ne sera plus affiché.
