### ISSUE TITLE
Îcone découpe d'image

### ISSUE THREAD

**Issue by gbert1** [dvoitsek/recolnat-lab#103]
Je ne comprends pas (on ne me rappelle pas) à quoi sert ce bouton ?
Par ailleurs, l'icône m'entraîne vers la découpe d'image.

**Comment by dvoitsek** [comment]
Quel bouton appellez-tu découpe d'image ?

**Comment by dvoitsek** [comment]
Suite à notre disuscussion d'hier, l'élément sera mis en évidence dans la paillasse quand on passe le curseur sur ses données dans les propriétés.
