### ISSUE TITLE
pp : date superflue pour la valeur ainsi qu'italiques

### ISSUE THREAD

**Issue by gbert1** [dvoitsek/recolnat-lab#107]
La date pour la valeur est superflue puisque la valeur date de la création. Or on a déjà la ligne donnant les date et heure de création.
La valeur peut être une ligne succédant immédiatement à la ligne "Création : lundi 19/09/2016 à 10:09" sous la forme : 
Création : lundi 19/09/2016 à 10:09
Longueur = 42.32 mm

Il vaudrait mieux l'écrire en normal et garder les italiques pour les commentaires.

<img width="366" alt="capture d ecran 2016-10-10 12 23 38" src="https://cloud.githubusercontent.com/assets/19670563/19233259/b9f98f02-8ee4-11e6-9ea2-8ac3f2f1e688.png">

**Comment by dvoitsek** [comment]
Fait.
