### ISSUE TITLE
pp : ne pas afficher pp de l'image si il y a un autre objet

### ISSUE THREAD

**Issue by gbert1** [dvoitsek/recolnat-lab#108]
Tu ne l'as pas fait encore, je le marque en bug pour que ce soit dans ta liste.

Afficher seulement les pp de l'objet sur lequel l'utilisateur vient de cliquer. 
Les pp de l'image sont affichées seulement qd on clique à un endroit sans autre objet (mesure ou autre).

**Comment by dvoitsek** [comment]
Fait.
