### ISSUE TITLE
Diminuer hauteur saisie commentaire

### ISSUE THREAD

**Issue by gbert1** [dvoitsek/recolnat-lab#109]
Passer la saisie de commentaire de 3 à 2 lignes — ou mieux encore diminuer l'interligne dans la fenêtre d'édition et conserver 3 lignes.
Ceci permettra de faire réapparaître ce qui est sous la fenêtre d'édition. Ainsi l'utilisateur comprendra que le nouveau commentaire vient se placer là, avant les précédents, si l'on est en antéchronologique.

Nota : Pourtant, il me semblait que la semaine dernière elles étaient affichées chronologiquement.

**Comment by dvoitsek** [comment]
Fait.

La semaine dernière, comme je l'avais expliqué de vive voix quand tu as posé la question, les annotations étaient rangées dans l'ordre alphabétiques des identifiants.

**Comment by gbert1** [comment]
J'hésite entre le chrono (le plus logique mais fastidieux) et l'antéchrono qui permet d'avoir le plus récent en haut sans scroller.
Qu'en penses-tu toi ?

**Comment by dvoitsek** [comment]
Je pense que commencer par le plus récent est
- plus utile pour anticiper le multi-utilisateurs (on voit les ajouts
  récents sans scroller)
- plus facile à comprendre pour l'ajout d'annotations (ça s'ajoute là où
  j'ai écrit mon texte), si on décide de mettre le volet "nouvelle
  annotation" en bas il faudra scroller en plus
- plus évident si les utilisateurs sont habitués à twitter, pinterest,
  google plus

**Comment by gbert1** [comment]
Je partage. Go pour l'antéchrono.
