### ISSUE TITLE
Mettre en place complètement le fonctionnement en Mode Agencement

### ISSUE THREAD

**Issue by gbert1** [dvoitsek/recolnat-lab#11]
En mode Agencement, on : 
1/ voit les planches en taille 400px
2/ peut les déplacer en cliquant n'importe où dessus
3/ 2xclique sur une planche alors on BASCULE EN MODE OBSERVATION sur cette planche

Le mode agencement est fait pour agencer sinon il n'a aucun intérêt.

Voici la description du mode Agencement tel que décrit dans mon document d'ergonomie : 

_On visualise un set de façon grossière (pas de vue détaillée) et on peut déplacer les planches sur la paillasse d’un clic, sans avoir à les sélectionner explicitement. En faire des groupes. Déplacer chacun de ces groupes._

[Harmonisation actions.pdf](https://github.com/dvoitsek/recolnat-lab/files/313523/Harmonisation.actions.pdf)

**Comment by dvoitsek** [comment]
1/ Je pense qu'il vaut mieux adapter la qualité au niveau de zoom. L'utilisateur peut, par exemple, même en mode agencement, avoir besoin de regarder un détail de près pour savoir dans quel groupe ranger sa planche. Devoir passer en mode observation pour regarder ça, puis en mode agencement à nouveau ne serait pas ergonomiquement simple.

2&3 / Ok

Je pense qu'il faut adapter le document d'ergonomie pour prendre en compte l'utilisation signalée en 1/

**Comment by gbert1** [comment]
Le mode agencement doit permettre d'agencer, de classer, de grouper, d'avoir une vue d'ensemble.
Le mode observation d'observer.
Si l'on introduit des fct de l'un dans l'autre, on rend l'IHM confuse.

**Comment by dvoitsek** [comment]
Quel est le problème ergonomique avec le fait d'afficher les images haute qualité quand c'est nécessaire dans le mode Agencement ?

**Comment by gbert1** [comment]
Il ne s'agit pas de ça.
Le besoin en mode agencement est de voir et manipuler les planches comme des cartes quand on joue à la réussite. De façon hyper fluide. De grouper, dégrouper, faire des amas.
Les planches doivent donc être ttes de même taille. On n'a pas besoin de les détail, AU CONTRAIRE. On veut voir toutes les images pour faire du classement.

Les 2 modes doivent être très différents, très tranchés ! 
Sinon, nous allons patauger !

**Comment by dvoitsek** [comment]
Je comprends bien à quoi sert le mode agencement, mais parfois les critères de groupement ne sont pas visibles sur des images basse/moyenne qualité et il faut bien basculer sur les images haute qualité, non ?

Si le fonctionnement actuel n'est pas fluide il faut m'indiquer à quel moment pour que je puisse optimiser là où c'est possible.

**Comment by gbert1** [comment]
Non, s'il manque des critères, alors l'utilisateur rebascule en mode observation (qui est dévolu à observer).
Il est possible que ds le futur, on aille effectivement ds le sens que tu indiques (output d'atelier), mais pour l'instant les 2 modes doivent être tranchés pour que l'utilisateur les appréhende intuitivement.

**Comment by dvoitsek** [comment]
Je pense qu'on a une incompréhension au niveau de ce qu'est le mode Agencement. Pour moi il ne s'agit pas d'un mode qui est issu purement d'une réflexion ergonomique : il s'agit d'un besoin métier. La segmentation que tu proposes est purement ergonomique et s'oppose au métier. Je propose de renommer le mode "Observation" en "Annotation" vu que dans les faits c'est l'usage métier.

**Comment by gbert1** [comment]
Le mode agencement correspond à la systématique.
Le mode observation à l'observation détaillée des spécimens, avec des outils.

**Comment by dvoitsek** [comment]
La systématique nécessite parfois de pouvoir examiner le détail d'une image pour savoir où la mettre, donc il n'est pas logique de quitter le mode agencement pour pouvoir le faire. Pourquoi ne pas renommer le mode "Agencement" en "Systématique" pour ne pas introduire de vocabulaire inutile et confus pour nos utilisateurs ?

**Comment by gbert1** [comment]
Pourquoi pas sur les intitulés, on verra. J'y réfléchirai.
En tout cas, je veux que l'on sépare vraiment ces 2 modes : fais-moi confiance.

**Comment by dvoitsek** [comment]
Le fonctionnement actuel (hormis les points 2&3 que je vais implémenter) respecte les besoins du métier, les contraintes de fluidité et de facilité d'utilisation. Le changement demandé s'oppose aux besoins du métier donc il va falloir plus que de la confiance en toi pour me convaincre de changer ça.

**Comment by dvoitsek** [comment]
2&3 implémentés en dev.
