### ISSUE TITLE
Caractères cabalistiques dans la ligne de titre du fichier export

### ISSUE THREAD

**Issue by gbert1** [dvoitsek/recolnat-lab#112]
voir pj

![capture d ecran 2016-11-16 16 22 22](https://cloud.githubusercontent.com/assets/19670563/20352838/1813a1c6-ac19-11e6-9779-f6deb918499b.png)

**Comment by dvoitsek** [comment]
J'ai essayé de changer des paramètre d'encodage. Teste pour voir si ça marche chez toi.

**Comment by dvoitsek** [comment]
Pas de nouvelles, je ferme ce ticket.
