### ISSUE TITLE
Images des planches non affichées à l'ouverture d'un set existant

### ISSUE THREAD

**Issue by gbert1** [dvoitsek/recolnat-lab#115]
Les images des planches du set ne sont pas affichées sur la paillasse à l'ouverture du set, sauf l'une d'elles.
Si l'on clique sur loupe, ça ne change rien.
Sur "Tout", non plus.
Seul le clic sur "Planche" force l'affichage des images.
Voir PJ

<img width="960" alt="capture d ecran 2016-11-18 16 53 10" src="https://cloud.githubusercontent.com/assets/19670563/20436231/afa8dfb4-adaf-11e6-8ad9-356ce811a0df.png">

**Comment by dvoitsek** [comment]
Normalement résolu.
