### ISSUE TITLE
Conversion pixels --> mm

### ISSUE THREAD

**Issue by gbert1** [dvoitsek/recolnat-lab#118]
Il me semble (en réfléchissant sur l'étalonnage) très dangereux de ne pas tenir compte de la possibilité d'un DPIy différent du DPIx.
Il est peu coûteux de l'implémenter maintenant comme un classique calcul de longueur dans l'espace préalablement orthonormé avec le facteur DPIx et le facteur DPIy : 

L = sqrt( (Xb - Xa)2 + (Yb - Ya)2 )

**Comment by dvoitsek** [comment]
Si on applique cet algo, ça veut dire qu'il faudra étalonner séparément les axes aussi ?

**Comment by gbert1** [comment]
Peut-être que oui.

**Comment by dvoitsek** [comment]
Marc ayant indiqué que les images sont orthonormées, ce changement n'est pas nécessaire.
