### ISSUE TITLE
Bouton "Planche" coupé

### ISSUE THREAD

**Issue by gbert1** [dvoitsek/recolnat-lab#121]
Centrer "Planche" sur le bouton pour qu'il ne soit pas coupé.

Voir PJ  : 

![capture d ecran 2016-11-29 15 53 39](https://cloud.githubusercontent.com/assets/19670563/20714607/d38f7e60-b64c-11e6-9884-34b2544591d3.png)

**Comment by dvoitsek** [comment]
Corrigé.
