### ISSUE TITLE
Affichage paillasse impossible pour les sets importés

### ISSUE THREAD

**Issue by gbert1** [dvoitsek/recolnat-lab#122]
J'ai créé 2 sets par imports CSV.
Un de 42 images, un de 5 images.
Celui de 5 images n'a eu aucune erreur à l'import. Ses 5 images s'affichent bien en miniatures dans le SM.
Mais  quand je clique sur placement (en grille ou en ligne), j'ai le message "Placement en cours" qui tourne sans s'arrêter et sans que mes images ne s'affichent jamais.

**Comment by dvoitsek** [comment]
C'est corrigé.
