### ISSUE TITLE
Suppression de set impossible (apparemment)

### ISSUE THREAD

**Issue by gbert1** [dvoitsek/recolnat-lab#123]
Je n'arrive pas à supprimer l'un de mes sets importé. 
Je n'ai pas essayé encore avec d'autres sets car je n'ai plus accès à les sets (plantage serveur ?).

**Comment by dvoitsek** [comment]
Je pense que tu viens de découvrir un bug grave (et de supprimer la racine de tes sets à cause du bug). Je viens d'arrêter tous les serveurs sauf le dev pour chercher la source.

**Comment by gbert1** [comment]
Voici ce que j'ai fait : 
1/ j'ai demandé la suppression du set avec le bouton contextuel rouge
2/ comme la roue tournait sans s'arrêter et qu'il y avait encore une boîte message, j'ai pensé qu'il me demandait de supprimer un à un les fichiers du set..... comme il en contenait bcp, j'ai cliqué une quinzaine de fois sur le bouton supprimer.....
Je ne sais pas si cela t'aide.

**Comment by dvoitsek** [comment]
Non, le problème c'est que pour une raison inconnue c'est le set parent qui a été supprimé et pas son contenu.

**Comment by dvoitsek** [comment]
Le problème est désormais résolu et les services sont de retour.
