### ISSUE TITLE
Login impossible car on reste tjrs dans le popup de login

### ISSUE THREAD

**Issue by gbert1** [dvoitsek/recolnat-lab#124]
Mon authentification fonctionne mais la popup de login reste affichée et l'appli continue à me demander de me loguer...

**Comment by gbert1** [comment]
Peut-être est-ce parce que tu es en train de tout redémarrer.....

**Comment by dvoitsek** [comment]
En effet comme je disais dans l'autre ticket, je viens d'arrêter tous les serveurs jusqu'à trouver la source du bug de suppression.
