### ISSUE TITLE
Mémoriser langue

### ISSUE THREAD

**Issue by gbert1** [dvoitsek/recolnat-lab#125]
Lorsque je ferai le design de la langue dans la barre de menu, il faudra mémoriser la langue de l'utilisateur pour qu'il n'ait pas à chaque log à rebasculer dans la langue de son choix.

**Comment by dvoitsek** [comment]
La langue est déjà mémorisée au niveau du Collaboratoire. Ce sera à chaque application de mémoriser ça de son côté.

**Comment by gbert1** [comment]
Il y a 2 problèmes en un seul  : 

Non, ça n'est pas mémorisé chez moi. J'ai testé avant de te le signaler : j'ai fermé complètement mon FF avant de le réouvrir.

Non, si l'on porte la langue dans la barre de menu du haut ce devra être mémorisé au niveau de Recolnat. Sinon l'utilisateur va devoir rechoisir sa langue 3 fois : portail, explore, collaboratoire ! 

De le porter dans la barre du haut le rendra très visible : actuellement c'est très caché dans toutes les applis. De toute façon pour le portail, on n'aura pas le choix.

**Comment by dvoitsek** [comment]
Ca veut dire que ton FF a vidé ton cache, donc la mémorisation de la langue a été perdue.

Si tu veux que ce soit mémorisé au niveau de Recolnat, il faut voir Julien & Simon vu qu'il n'y a pas de "stockage global Recolnat" des paramètres utilisateur.

Je n'ai rien contre le porter dans la barre de menu, il faut juste se rappeler que la barre est un composant passif, elle ne mémorise rien et n'agit que à travers des applis qui l'accueillent.
