### ISSUE TITLE
Rendre visible le portoir d'icônes contextuelles

### ISSUE THREAD

**Issue by gbert1** [dvoitsek/recolnat-lab#126]
La rosace d'icônes contextuelles n'est pas compréhensible car il y a souvent que 2 ou 3 icônes... parfois même une seule ! C'est le cas dans le SM. Qd on clique droit sur un set, il n'y a que l'icône rouge. Dans ce cas cette icône qui apparaît seule et à distance du pointeur de la souris est déconcertante.
Je te propose de rendre légèrement visible le disque sur lequel sont posés ces (cette) icône(s). Ainsi l'utilisateur comprendra qu'il s'agit d'un ensemble. Cette légère visibilité peut sans doute être obtenue par une opacité (par exemple de 50%) appliquée à un cercle empli de blanc ou autre couleur.

**Comment by dvoitsek** [comment]
Fait.
