### ISSUE TITLE
Règle en mm par défaut

### ISSUE THREAD

**Issue by gbert1** [dvoitsek/recolnat-lab#13]
La règle doit être par défaut en mm.

**Comment by dvoitsek** [comment]
Les mesures sont déjà en mm par défaut... tu es sûr que l'image que tu utilises a des données EXIF ?

**Comment by gbert1** [comment]
Oui.
vérifie, c'est : MNHN P05559976

**Comment by dvoitsek** [comment]
La mesure est affichée en mm par défaut chez moi. Par contre le menu déroulant sous l'outil indique en effet le mauvais étalon.
