### ISSUE TITLE
impossible de sortir de la boîte connexion

### ISSUE THREAD

**Issue by gbert1** [dvoitsek/recolnat-lab#130]
Dmitri, Que faut-il faire quand j'ai ce genre d'écran ci-dessous et que je réussis pas à rentrer dans le collaboratoire ?

<img width="1280" alt="capture d ecran 2017-01-09 17 06 30" src="https://cloud.githubusercontent.com/assets/19670563/21773134/2ef26ebe-d68e-11e6-8a92-99ec811aca94.png">

**Comment by dvoitsek** [comment]
Il faut verifier l'état du serveur sur https://wp5test.recolnat.org/status/

En l'occurrence labo-test est offline depuis l'année dernière pour économiser les ressources du serveur (avec l'espoir que lab/vm plante moins souvent en conséquence)..

**Comment by gbert1** [comment]
Ok, au temps pour moi, je croyais qu'il était encore en fonction.
