### ISSUE TITLE
Position bouton étalonnage + info sur la conversionutilisée

### ISSUE THREAD

**Issue by gbert1** [dvoitsek/recolnat-lab#133]
La position du bouton "étalonnage" en-dessous laisse accroire que l'étalonnage est dans le flux de la mesure, à savoir qu'on mesure, puis qu'on appuie sur ce bouton.

D'un pt de vue ergo, les 2 choses suivantes sont plus claires : 
1/ au-dessus, une indication de la source de la conversion utilisée, soit exif, soit étalon planche (voir mockup)
2/ au-dessus encore, le bouton ou l'onglet pour accéder à la partie étalonnage

**Comment by dvoitsek** [comment]
Déplacé au-dessus
