### ISSUE TITLE
Règle : pb après enregistrement

### ISSUE THREAD

**Issue by gbert1** [dvoitsek/recolnat-lab#14]
Quand on valide l'intitulé de la mesure, cela provoque 2 actions.
1/ l'enregistrement de cet intitulé, ça c'est ok
2/ la pose du 1er point d'une nouvelle mesure à cet endroit-là, ça c pas ok

Il faut que slt 1/ se produise et que pour démarrer une nouvelle mesure, on clique explicitement ailleurs.

**Comment by dvoitsek** [comment]
Corrigé en dev en même temps qu'un bug qui empêchait l'enregistrement d'avoir lieu.
