### ISSUE TITLE
Inspecteur inactif

### ISSUE THREAD

**Issue by gbert1** [dvoitsek/recolnat-lab#16]
L'inspecteur n'affiche rien. Est-ce parce que tu termines son développement ?

**Comment by dvoitsek** [comment]
Le développement de l'inspecteur est terminé. S'il n'affiche aucune mesure ni annotation pour certains éléments (par exemple les images ou les sets) c'est parce qu'il n'y a pas de mesures ni d'annotations disponibles. 

Par contre si le titre de l'inspecteur reste sur "Inspecteur d'éléments" quel que soit l'élément sur lequel tu cliques, c'est un bug et il faut me dire ce que tu cherches à inspecter pour que je puisse tester.

**Comment by gbert1** [comment]
Actuellement, je ne parviens jamais à obtenir qq chose ds cet inspecteur.
L'inspecteur doit afficher les détails de chaque mesure qd je la pointe, c'est ce qui était convenu. Et c'est ce que l'on attend d'un inspecteur.
Idem des POI, des zones, etc.

**Comment by dvoitsek** [comment]
Et c'est bien ce qu'il fait (cf image provenant de la version déployée en test
![inspector](https://cloud.githubusercontent.com/assets/8166976/16039328/6d469cd0-3229-11e6-9cde-7bf39c30fd5f.png)
)

**Comment by gbert1** [comment]
ça ne marche pas chez moi.
J'ai beau balader mon curseur sur les mesures et les POI et les zones, je n'ai rien.

**Comment by dvoitsek** [comment]
Il faut cliquer sur l'objet à examiner.

**Comment by gbert1** [comment]
bien sûr que j'ai essayé de cliquer :) 
c'est même le mode attendu

**Comment by dvoitsek** [comment]
Pardon, j'avais juste mal compris le verbe "balader" :) Est-ce que le titre dans l'inspecteur (à côté du panneau chantier) change ?

**Comment by gbert1** [comment]
non, non, rien ne change

**Comment by dvoitsek** [comment]
Ca ça peut vouloir dire que tu dois être sur une ancienne version dans le cache de ton navigateur.

**Comment by dvoitsek** [comment]
... ou alors sur une tablette ?
