### ISSUE TITLE
Mesures illisibles en mode planche

### ISSUE THREAD

**Issue by gbert1** [dvoitsek/recolnat-lab#17]
Les mesures sont illisibles en mode planche.
Alors que l'on est susceptible de faire des mesures sur toute la largeur ou toute la hauteur de la planche.

**Comment by dvoitsek** [comment]
3 solutions possibles :
1/ Adapter les mesures au niveau de zoom mais si les mesures sont grandes, elles vont cacher la planche et les autres mesures.
2/ Laisser tel quel et forcer l'utilisateur à zoomer sur la valeur de la mesure.
3/ Afficher la mesure en tooltip quand l'utilisateur passe son curseur dessus, mais ça ne marche pas pour le tactile, et l'utilisateur ne sera pas au courant que c'est possible avant d'avoir essayé.

Quelle combinaison de défauts préfères-tu ?

**Comment by gbert1** [comment]
Solution 1/

**Comment by dvoitsek** [comment]
Implémenté en dev et basculé en test avec tous les autres changements.
