### ISSUE TITLE
Bug pendant le placement --> Erreur

### ISSUE THREAD

**Issue by gbert1** [dvoitsek/recolnat-lab#2]
Avec le message suivant :
"Erreur pendant le placement: Error: Internal Server Error"

<img width="960" alt="capture d ecran 2016-06-02 17 42 55" src="https://cloud.githubusercontent.com/assets/19670563/15751474/8a148c16-28ea-11e6-9dd9-10d3e52fe7f8.png">

**Comment by dvoitsek** [comment]
Placement automatique (si oui, en ligne ou en colonne ?) ou manuel ?

**Comment by gbert1** [comment]
J'ai la même erreur en ADSL ds Chrome : voir copie écran
<img width="1280" alt="capture d ecran 2016-06-03 11 17 43" src="https://cloud.githubusercontent.com/assets/19670563/15774504/01347d14-297d-11e6-9d77-60c8aa10abfd.png">

**Comment by dvoitsek** [comment]
Du coup je déduis par rapport aux autres tickets que c'est le placement manuel qui échoue. Je vais régler ça.

Est-ce que tu as une préférence en terme d'ergonomie entre le fonctionnement actuel (glisser pour placer) ou un bouton "+" pour ajouter i'image au centre de la vue ?

**Comment by gbert1** [comment]
Ne t'inquiète pas, les utilisateurs ont l'habitude.
Je ne connais aucun logiciel où l'utilisateur doive placer les éléments qu'il charge.
Dans tous ceux que j'utilise, les éléments sont placés arbitrairement sur la surface de travail.
Ensuite, l'utilisateur les réagence comme il a envie.

**Comment by dvoitsek** [comment]
Corrigé en dev
