### ISSUE TITLE
Rectangle invisible qd chagmt planche minivue

### ISSUE THREAD

**Issue by gbert1** [dvoitsek/recolnat-lab#21]
Qd on change de planche ds la minivue le rectangle rouge disparaît alors qu'il devrai têtre visible.

**Comment by dvoitsek** [comment]
Le rectangle rouge indique la partie qu'on est en train d'observer. SI le rectangle rouge n'apparait pas c'est que l'utlisateur regarde une zone dont les bords ne sont pas dans la minivue.

**Comment by gbert1** [comment]
vu hier, oui
je m'interroge sur une façon de signifier que les deux ne correspondent plus : minivue différente de paillasse
je n'ai pas d'idée

**Comment by dvoitsek** [comment]
Qu'est-ce que tu penses d'afficher une flèche sur un des bords de la minivue pour indiquer dans quelle direction se trouve la vue ?

**Comment by gbert1** [comment]
Oui, je pensais de colorer en rouge la ligne du bord de la minivue dans la direction où est ce qui est sur la paillasse.
Par exemple, le bord gauche si la planche ds la minivue est à droite de ce qui est visible sur la paillasse.
Par exemple, le bord bas si la planche ds la minivue est au-dessus de ce qui est visible sur la paillasse.
Etc.
Juste un trait rouge remplaçant le trait normal ou alors un trait rouge à l'intérieur, collé à la bordure.
