### ISSUE TITLE
SM : glisser-déposer entre colonnes provoque 404

### ISSUE THREAD

**Issue by gbert1** [dvoitsek/recolnat-lab#29]
Voir copie écran ci-dessous : 
le glisser d'une image de la colonne "Racine des sets" à la colonne "Pivoines" provoque une 404

![capture d ecran 2016-06-17 12 26 46](https://cloud.githubusercontent.com/assets/19670563/16148134/e080c382-3487-11e6-911a-4908d17bdde5.png)

**Comment by dvoitsek** [comment]
Bug non reproductible.

**Comment by dvoitsek** [comment]
Fermeture car non reproductible.
