### ISSUE TITLE
Distinguer les titres des colonnes du gestionnaire de set

### ISSUE THREAD

**Issue by gbert1** [dvoitsek/recolnat-lab#3]
Pourrais-tu "styler" les titres (et le fond de la case les contenant) des colonnes du gestionnaire de set de la façon suivante : 
1/ en gras
2/ hauteur correspondant à une seule ligne et non à plusieurs comme actuellement (si un nom de ste est long alors il faudra agrandir cette hauteur ou alors abréger le titre (perso, je préfére cette solution d'abréger))

<img width="541" alt="capture d ecran 2016-06-03 11 24 41" src="https://cloud.githubusercontent.com/assets/19670563/15774665/d7c660cc-297d-11e6-8aa1-d17303f93a97.png">

**Comment by dvoitsek** [comment]
1/ Ok

2/ Le problème c'est la languette permettant de fermer le volet de gauche (idem pour celui de droite). Si je fais le titre sur une seule ligne une partie des noms des premiers éléments seront cachés par la languette. Si je remonte la languette, c'est le nom du set qui est caché.

As-tu une idée pour gérer le problème ?

**Comment by gbert1** [comment]
3 solutions :
1/ raccourcir la longueur de la languette de moitié
2/ utiliser un effet de transparence, l'utilisateur sait de toute façon ce qu'il y a dessous, il est capab le de le reconstruire à partir de la suite, comme dans ces tests où l'on masque la partie basse d'un mot
2/ intégrer la languette au panneau qd il est déplié.

**Comment by dvoitsek** [comment]
Corrigé dans la version de dev.
