### ISSUE TITLE
Panier Explore non vidé alors que planches ajoutées dans SM

### ISSUE THREAD

**Issue by gbert1** [dvoitsek/recolnat-lab#33]

**Comment by dvoitsek** [comment]
Une description plus détaillée du problème et de la solution demandée est nécessaire

**Comment by gbert1** [comment]
Peux-tu me l'assigner, je ne sais pas comment faire. Sans doute parce que je n'ai pas les droits suffisants.

**Comment by dvoitsek** [comment]
Je ne peux pas te l'assigner : tu dois d'abord accepter l'invitation à participer au projet.

**Comment by dvoitsek** [comment]
Ca a l'air d'avoir été corrigé des deux côtés.
