### ISSUE TITLE
SM : ôter "image de"

### ISSUE THREAD

**Issue by gbert1** [dvoitsek/recolnat-lab#36]
Ôter les mots "image de" ds le volet de droite du SM.
Cela prend de la place au détriment de la suite du nom.

<img width="355" alt="capture d ecran 2016-06-17 13 16 26" src="https://cloud.githubusercontent.com/assets/19670563/16148980/b70680fe-348d-11e6-9b78-10763ed5b0d5.png">

**Comment by dvoitsek** [comment]
Clone de #39

**Comment by gbert1** [comment]
Je ne comprends pas cette distinction spécimen / image.
L'objectif justement de Recolnat est d'avoir une image numérisée par spécimen.
Si tu tiens absolument à mentionner que ce sont des images, met le en haut "Images du set Pivoines"

**Comment by dvoitsek** [comment]
On peut avoir plusieurs images par spécimen Explore.

**Comment by gbert1** [comment]
Oui. Mais il n'y a que des images. Il n'y a pas de sculptures de spécimens. D'impressions 3D de spécimens.

**Comment by dvoitsek** [comment]
Implémenté en dev.
