### ISSUE TITLE
SM : ôter le petit panneau jaune

### ISSUE THREAD

**Issue by gbert1** [dvoitsek/recolnat-lab#37]
Il angoisse.
L''image de toute façon est petite, donc déjà de piètre qualité.

<img width="355" alt="capture d ecran 2016-06-17 13 16 26" src="https://cloud.githubusercontent.com/assets/19670563/16149020/0daf8ed2-348e-11e6-9108-837f2e843d44.png">

**Comment by dvoitsek** [comment]
Pendant l'atelier, sur le carrousel d'images, les utilisateurs se sont souvent exclamés "mais c'est trop petit, on ne peut pas travailler dessus", il peut donc être utile de préciser que cette zone n'est pas prévue pour faire du travail dessus.

**Comment by gbert1** [comment]
Dans ce cas, remplace le panneau par la mention : "Aperçu"

**Comment by dvoitsek** [comment]
Changé en dev
