### ISSUE TITLE
SM : afficher le nb de planches du set sélectionné

### ISSUE THREAD

**Issue by gbert1** [dvoitsek/recolnat-lab#38]
Afficher dans l'inspecteur de droites le nb d'images que contient le set.
L'afficher entre le titre de la boîte et la liste des images sous la forme : 17 images

<img width="365" alt="capture d ecran 2016-06-17 13 22 57" src="https://cloud.githubusercontent.com/assets/19670563/16149102/9efdea32-348e-11e6-993c-6dd720c19f6b.png">

**Comment by dvoitsek** [comment]
Implémenté en dev
