### ISSUE TITLE
Paillasse : Resserrer le titre des planches

### ISSUE THREAD

**Issue by gbert1** [dvoitsek/recolnat-lab#39]
Oter "Image de" dans le titre des planches dans le cas où cela ne vient pas de la base de Julien.
Utiliser une police maigre.
Utiliser une police narrow.
Utiliser une police plus petite.

<img width="786" alt="capture d ecran 2016-06-17 13 44 19" src="https://cloud.githubusercontent.com/assets/19670563/16149623/6a36c5ae-3492-11e6-9f45-49252e918977.png">

**Comment by dvoitsek** [comment]
Dans la base de Julien les images n'ont pas de titre.
