### ISSUE TITLE
Perte planche lors du passage de "1:1" à "Planche" 

### ISSUE THREAD

**Issue by gbert1** [dvoitsek/recolnat-lab#4]
Si l'on est en affichage 1:1 sur un détail d'une planche
et que l'on clique sur "Planche"
alors on n'a plus rien, les planches deviennent toutes petites en haut à gauche
au lieu que l'on ait l'affichage de la planche que l'on était en train d'étudier

**Comment by dvoitsek** [comment]
Corrigé dans la version de dev.
