### ISSUE TITLE
Métadonnées

### ISSUE THREAD

**Issue by gbert1** [dvoitsek/recolnat-lab#40]
> Mettre un prompt devant leur titre
> 
> Affichage : 
> Diminuer la taille de police à 10.
> Diminuer le padding, le margin, tout ce qui peut l'être pour avoir des lignes sur une seule ligne

**Comment by dvoitsek** [comment]
Voici le résultat si j'applique les modifications demandées. Est-ce que tu veux **vraiment** garder ça ?
![metadata](https://cloud.githubusercontent.com/assets/8166976/16190085/cc379858-36dd-11e6-8e80-8558a7083b79.jpeg)

**Comment by gbert1** [comment]
Oui. Ça m'a l'air bien en taille. Par contre c'est toujours en gras. Peux-tu le mettre en maigre ?
Par contre (n°2 :-) ), il faut tout de même le symbole deux points entre Nom scientifique et Calamintha 
Nom scientifique : Calamintha
Genre : Calamintha

**Comment by dvoitsek** [comment]
Pour la taille je tiens à préciser que je dois me tenir à moins de 10cm de l'écran pour arriver à lire... mais visiblement le confort visuel n'est pas une priorité. Je bascule en Vm du coup.

Ce n'est pas en gras, c'est en standard, donc je ne comprends pas ce que tu veux dire par "mettre en maigre".

Je ne peux pas insérer ce ":", il s'agit d'une table et il y a toujours des cellules qui font plus que deux lignes, donc ce sera horrible.

**Comment by gbert1** [comment]
On réglera ça de visu, c'est le cas de le dire :-)
