### ISSUE TITLE
Les POI ne fonctionnent pas (11h16)

### ISSUE THREAD

**Issue by gbert1** [dvoitsek/recolnat-lab#44]
J'ai vu que tu avais fermé le bug, l'ayant sans doute corrigé. Pourtant ça ne marche toujours pas de mon côté.

**Comment by dvoitsek** [comment]
"Corrigé en dev" veut dire que c'est corrigé dans la version de dev (qui tourne sur /labo-dev et qui est toujours en travaux). Je bascule en test et/ou en prod quand ma liste de choses à corriger est vide ou que c'est urgent ET j'envoie un mail aux concernés (Manuel et toi).

Par contre ce serait gentil de ne pas ouvrir de nouveaux tickets et de réouvrir les anciens si le problème se présente, ça facilite énormément l'organisation du travail.

**Comment by gbert1** [comment]
J'ai cherché à le réouvrir mais je n'y ai pas réussi.
Apparemment, je n'ai pas accès à certaines fonctions.

**Comment by dvoitsek** [comment]
Tu n'as toujours pas accepté l'invitation à collaborer que tu as dû reçevoir sur ta boite gmail et/ou que tu peux retrouver dans ton profil github. Tant que tu n'as pas accepté cette invitation tu ne peux que ouvrir et commenter les tickets. Je te propose de découvrir ensemble la gestion de tickets quand tu auras le temps après la livraison.
