### ISSUE TITLE
SM : faciliter son usage pour les nouveaux utilisateurs

### ISSUE THREAD

**Issue by gbert1** [dvoitsek/recolnat-lab#45]
1/ Remplacer "Racine des sets" par "Mes sets"

2/ Bulle avec philactère tirée de Semantic UI (label) placée à droite du + de la colonne 1 qd on arrive ds le SM avec ce message : New set

3/ Clic sur le + de la colonne n°2 : ouvrir la boîte directement sur l'onglet panier

4/ Double clic sur titre colonne (sauf racine) : affiche le set

5/ Bouton "Panier Explore" sous les 4 boutons des modes : qd on clique dessus : 
a/ il ouvre directement le panier et le fait mouliner sans qu'on ait à cliquer sur Refresh
b/ le panier contient un champ "Nouveau sous set" que l'utilisateur doit remplir
c/ le set est mis par défaut à la racine

<img width="631" alt="capture d ecran 2016-06-20 15 21 50" src="https://cloud.githubusercontent.com/assets/19670563/16195629/d68ee366-36fa-11e6-8de8-7ddc683e2b58.png">

**Comment by dvoitsek** [comment]
Points 1 & 2 implémentés en dev et mis en prod Vm.

**Comment by gbert1** [comment]
doubler la taille de la bulle en grossissant le texte
la colorer dans le même vert que le +

**Comment by gbert1** [comment]
développer automatiquement le contenu de mes sets dans la première colonne

**Comment by dvoitsek** [comment]
Développement auto implémenté en dev.
