### ISSUE TITLE
Resserer encore le texte spécimen et élargir la colonne de gauche

### ISSUE THREAD

**Issue by gbert1** [dvoitsek/recolnat-lab#46]
Resserer encore le texte spécimen avec un line-height de 10px

Elargir de 50% la colonne de gauche

le but est d'avoir le max d'infos sous les yeux

<img width="1050" alt="capture d ecran 2016-06-20 15 48 07" src="https://cloud.githubusercontent.com/assets/19670563/16196539/af2787e8-36fe-11e6-84ad-22e8306839ef.png">

**Comment by dvoitsek** [comment]
Fait en dev
