### ISSUE TITLE
Rajouter Version ds le menu barbeQ

### ISSUE THREAD

**Issue by gbert1** [dvoitsek/recolnat-lab#52]
Attention, menu barbeQ inactif actuellement (j'ouvre un autre ticket).

Dans le menu barbecue, rajouter Version qui affichera une boîte version avec avertissement sur données  pouvants être effacées pendant phase béta.

**Comment by dvoitsek** [comment]
Il me semble qu'on avait clairement décidé qu'à partir de la Vm on garantissait la persistence des données entre versions...

**Comment by gbert1** [comment]
Oui. Mais c'est au cas où tu serais obligé de les effacer ;-)

**Comment by dvoitsek** [comment]
Les données ne seront plus jamais effacées (en prod), si une modification de la structure de la base est nécessaire il sera impératif de réserver du temps pour traiter les données eixstantes pour en éviter la perte.
