### ISSUE TITLE
menu barbeQ inactif

### ISSUE THREAD

**Issue by gbert1** [dvoitsek/recolnat-lab#53]
Attention, menu barbeQ inactif actuellement (j'ouvre un autre ticket).

**Comment by dvoitsek** [comment]
Oui, c'est normal, l'ergonomie du menu la plus récente que j'ai n'est pas à jour vis-à-vis des modes et n'est pas très claire pour l'utilisateur en fonction du mode dans lequel il est.

J'ai préféré désactiver le menu dans la Vm plutôt que d'entrainer de la confusion, en attendant une mise à jour.

**Comment by dvoitsek** [comment]
Menu réactivé en dev. Apparence et contenu dans l'image ci-dessous.

![mainmenu](https://cloud.githubusercontent.com/assets/8166976/16489425/bd6ea6a4-3ed5-11e6-9db7-b14c4465c47a.jpeg)
