### ISSUE TITLE
Import images à remettre

### ISSUE THREAD

**Issue by gbert1** [dvoitsek/recolnat-lab#54]
tu l'as retiré sans doute pour une raison

**Comment by dvoitsek** [comment]
Parce que ce n'est pas implémenté dans la Vm. C'est pour la V1.

**Comment by gbert1** [comment]
Si ça fonctionne, pourquoi le retirer ?

**Comment by dvoitsek** [comment]
Ce n'est pas implémenté = ça ne fonctionne pas.

**Comment by gbert1** [comment]
Mais, remarque Marc, ça marchait dans la version précédente. Tu as été obligé de le casser, c'est ça ?

**Comment by dvoitsek** [comment]
Tout à fait, à la demande de Marc pour avoir une livraison le plus tôt possible.

**Comment by gbert1** [comment]
Mais il marchait bien !
Je ne comprends pas. On en parle tout à l'heure, tu m'expliqueras.

**Comment by gbert1** [comment]
C'est une fonction hyper utile.

**Comment by dvoitsek** [comment]
Du coup quelle est l'IHM de cette fonctionnalité ?

**Comment by gbert1** [comment]
Je vais faire un mockup.
En même temps, je ferai la boîte "Version".
Nous mettrons l'accès à ces 2 fonctions dans le barbecue.

**Comment by dvoitsek** [comment]
L'import est de retour donc je ferme ce ticket.
