### ISSUE TITLE
Prise en mains SM : boutons + boîtes explicites

### ISSUE THREAD

**Issue by gbert1** [dvoitsek/recolnat-lab#55]
Pour que le nouvel utilisateur sache quoi faire : 
(voir mockups en PJ)

1/ Ajout de boutons explicites à gauche

2/ Ajout de 3 boîtes : 
— boîte "Nouveau set"
— boîte "Renommer set"
— boîte "Supprimer set"

![new set](https://cloud.githubusercontent.com/assets/19670563/16230994/62df32d4-37c4-11e6-9e80-0efba4ede5e7.png)
![renommer set](https://cloud.githubusercontent.com/assets/19670563/16230995/62fd5c64-37c4-11e6-8393-d8aa8383093f.png)

**Comment by dvoitsek** [comment]
Je pense qu'on devrait rediscuter de la partie tutoriel + aide en ligne en équipe, j'ai aussi quelques propositions pour ça.

**Comment by gbert1** [comment]
Texte en haut boîte : 
Le nouveau set sera rajouté dans la première colonne. Vous pourrez le déplacer à l'intérieur d'une autre colonne (c'est-à-dire du set correspondant).

**Comment by dvoitsek** [comment]
Implémenté en dev
