### ISSUE TITLE
Agencement : supprimer la partie "Groupe" dans la palette

### ISSUE THREAD

**Issue by gbert1** [dvoitsek/recolnat-lab#56]

**Comment by dvoitsek** [comment]
Si une image est sélectionnée par défaut au chargement, est-ce encore nécessaire ?

**Comment by dvoitsek** [comment]
A défaut de réponse, supprimé en dev

**Comment by gbert1** [comment]
Je ne comprends pas la question. Par contre, le comportement que j'ai vu hier : à savoir ouverture paillasse avec image du milieu sélectionnée est très satisfaisante (j'avais un set de 6 et il était sur la 4 je crois).

**Comment by dvoitsek** [comment]
Ok, du coup je remets la partie "Groupe"

**Comment by gbert1** [comment]
Parlons-en de vive voix demain parce que je ne comprends pas ce qu'il peut y avoir à ce stade dans "Groupe".
