### ISSUE TITLE
Bouton "Ouvrir set"

### ISSUE THREAD

**Issue by gbert1** [dvoitsek/recolnat-lab#59]
Sous le bouton "Nouveau set", ajouter le bouton suivant : 

**Ouvrir le set**  (en gros)
sélectionné sur la paillasse      (en petit)

de couleur plus discrète, par exemple grise.

**Comment by dvoitsek** [comment]
Le texte formaté sur deux lignes peut prêter à confusion : est-ce qu'on ouvre "le set sélectionné" "sur la paillasse" ou "le set" (lequel?) "sélectionné sur la paillasse" ?

**Comment by dvoitsek** [comment]
Implémenté en dev.

**Comment by gbert1** [comment]
ça peut être aussi

Ouvrir (en gros)
le set sélectionné sur la paillasse (en petit)

il faut absolument qu'il y ait "set sélectionné"
