### ISSUE TITLE
Ouvrir paillasse depuis SM (set manager) en 2xcliquant sur aperçu planche

### ISSUE THREAD

**Issue by gbert1** [dvoitsek/recolnat-lab#6]
Pour répondre à la demande de Manuel, voici ce que je propose : 

qd l'utilisateur double clique sur un aperçu ds le SM (set manager), alors : 

1/ on affiche la paillasse CENTRÉE sur cette planche 
2/ avec le zoom "planche"

**Comment by dvoitsek** [comment]
Les problèmes suivants doivent être résolus avant :
a/ L'enchainement d'opérations proposé est complexe à exécuter, donc ce ne sera certainement pas pour la Vm.
b/ L'utilisateur aura plusieurs vues, laquelle afficher ?
c/ (à supposer qu'on résolve b) La planche peut ne pas être visible dans la vue choisie (que ce soit parceque l'utilisateur ne l'a pas placée, ou parce que l'utilisateur l'a enlevée de la vue mais l'a conservée dans le set pour d'autres vues).

**Comment by gbert1** [comment]
a/ ergonomiquement, c'est simple : veux-tu dire que techniquement c'est compliqué ? 

b/ la dernière vue utilisée

c/  on ne traite pas ce cas pour l'instant : on n'aura pas ce cas dans l'immédiat

**Comment by dvoitsek** [comment]
a/ Oui, je parle d'un point de vue technique.
b/ La sauvegarde de la configuration utilisateur n'est pas prévue pour la Vm.
c/ On a déjà ce cas dans l'immédiat dans (au moins) les situations suivantes : 
- Les images ne sont pas encore placées, donc l'image n'a pas de coordonnées.
- L'utilisateur choisit d'enlever une image de la vue.

**Comment by gbert1** [comment]
a/ est-il au moins possible de simuler le clic sur "Tout", ou encore mieux sur "Planche" ?

b/ pourtant tu as bien mis en place la persistance, je ne comprends pas pourquoi ce serais coûteux en temps de persister également les variables ergonomiques

c/ ne nous occupons pas de ce cas maintenant, ça va nous consommer du temps de discussion, d'échange, etc. remettons-le à plus tard

**Comment by dvoitsek** [comment]
a/ Le "Tout" oui. Le "Planche" non.

b/ La persistance actuelle est pour les données métier.

Ok, on remet à plus tard. Pour le moment je vais enlever les images du SM, ça a l'air de créer des confusions dans l'esprit de l'utilisateur.

**Comment by gbert1** [comment]
Non, n'enlève pas les images du SM : c'est une fonctionnalité essentielle.

Étend la persistance, c'est qq chose de primordial : cela va sans cesse nous bloquer côté ergo.

**Comment by dvoitsek** [comment]
Je rappelle le tableau de hiérarchisation du développement: "Ergonomie + zoning split + profil User : V2". Si je commence à implémenter la persistance des données d'ergonomie (il s'agit d'une nouvelle implémentation, pas d'une simple extension) on ne livre pas avant mi-juillet.

**Comment by gbert1** [comment]
j'ai discuté de ce ticket avec Manuel (qui en est l'origine) : il est OK pour que tu implémentes a/

Je rappelle ce qu'est a/ : 

a/ est-il au moins possible de simuler le clic sur "Tout", ou encore mieux sur "Planche" ?

**Comment by dvoitsek** [comment]
Implémenté en dev.

**Comment by gbert1** [comment]
super, je peux regarder depuis https://wp5test.recolnat.org/labo-test/ ?
