### ISSUE TITLE
Placement 

### ISSUE THREAD

**Issue by gbert1** [dvoitsek/recolnat-lab#60]
Je préférerais un placement complètement automatique. On arriverait ainsi directement sur les planches avec un clic de moins et de façon plus spectaculaire.
L'utilisateur peut déplacer les images ensuite, comme l'a souligné Manuel.

Si tu souhaitais tout de même rester sur un placement manuel, alors il faudrait que cette interactivité soit bcp plus évidente pour l'internaute (le bouton en bas à gauche est pas facile à trouver et à en comprendre le sens, ceci parmi tout le reste de l'interface). Il faut le mettre au centre de la paillasse avec une invite.

**Comment by dvoitsek** [comment]
Autrement dit quand l'utilisateur enlève une image d'une vue du set, il aura un gros bouton au milieu de l'écran lui demandant de placer une image même s'il n'a pas envie de la voir.

**Comment by gbert1** [comment]
C'est au moment où l'on vient de créer un set.

**Comment by dvoitsek** [comment]
Fait en dev. Le bouton est plus visible et le texte est plus détaillé.

**Comment by gbert1** [comment]
Si nous gardons ce choix dans la la V1, il faudrait au moins rendre plus explicite les deux boutons Ligne et Colonne, qui sont pas mal énigmatiques, il vaudrait mieux mettre "En ligne" et "En colonne"
Je persiste à penser que cette décision demandée à l'utilisateur est un clic qui pourrait être évité. Dans la mesure où il peut très facilement maintenant déplacer les images à la main après leur placement automatique.
Elle le sera encore moins quand tu réussiras à faire le placement automatique en matrice.

**Comment by dvoitsek** [comment]
Il y a déjà du placement auto en matrice.

**Comment by gbert1** [comment]
Ouaouh, super, je suis impatient de l'utiliser parce que c'est chouette de remplir l'écran de planches variées.

**Comment by dvoitsek** [comment]
Alors n'hésite pas à l'utiliser : c'est en test depuis un moment.
