### ISSUE TITLE
4 bugs "Nouveau set" paillasse

### ISSUE THREAD

**Issue by gbert1** [dvoitsek/recolnat-lab#61]
Le bouton "Nouveau set" sur la paillasse contient 4 bugs : 

1/ si on n'a rien sélectionné de nouveau, il affiche l'ancienne sélection

2/ si 'efface cette sélection, il affiche rien et l'internaute ne comprend pas : il faut lui afficher d'aller sélectionner dans Exmplore

3/ si on va sélectionner ds Explore, alors la nouvelle sélection s'ajoute à la précédente et il faut supprimer la nouvelle

4/ on reste éternellement avec le message "Création du set" et la roue qui tourne.

**Comment by dvoitsek** [comment]
Est-ce que tu peux détailler les actions à faire pour reproduire chacun de ces 4 bugs ?

**Comment by gbert1** [comment]
J'étais sur la paillasse avec un set de 6 planches. J'ai cliqué sur le bouton "Nouveau set" à gauche, au-dessus de la minivue.

**Comment by dvoitsek** [comment]
Ah, je comprends mieux, le bouton ne doit pas apparaître ailleurs que dans le mode Set.

**Comment by gbert1** [comment]
Bo.... ça se discute....ça pourrait être une idée de le laisser aussi sur la paillasse... mais je n'en suis pas sûr..... de toute façon comme ils sont passés forcément une fois par le mode set manager, ils en connaissent l'existence et ferons l'effort cognitif d'y retourner. On peut donc tout à fait le retirer avec la boîte Actions qui l'englobe.

**Comment by dvoitsek** [comment]
Corrigé en dev et déployé en test.
