### ISSUE TITLE
1:1 ne conserve pas le centrage

### ISSUE THREAD

**Issue by gbert1** [dvoitsek/recolnat-lab#63]
Si j'ai cliqué sur "Planche" puis que je clique sur "1:1", le zoom n'a pas lieu sur le centre de la planche mais sur son coin bas droit.

Idem si je clique sur 'Tout" et que je sélectionne une des planches (y compris la centrale) et que je clique sur "1:1"

**Comment by dvoitsek** [comment]
Corrigé en dev
