### ISSUE TITLE
Mettre à jour l'inspecteur qd je clique sur une planche

### ISSUE THREAD

**Issue by gbert1** [dvoitsek/recolnat-lab#64]
Qd je "sélectionne" une planche, l'inspecteur devrait/doit afficher toutes les mesures et tout ce qui a été fait sur la planche.

**Comment by dvoitsek** [comment]
Il me semblait qu'on s'était mis d'accord que l'inspecteur affiche le local, et la liste des mesures d'une planche est affichée non pas dans l'inspecteur mais dans le composant qui liste toutes les mesures, tags et annotations d'un set ou d'une planche.

**Comment by gbert1** [comment]
Tu as raison : j'ai confondu les deux. Sans doute parce que la liste des mesures n'existe pas encore.
