### ISSUE TITLE
Mettre à jour inspecteur qd on enregistre une nouvelle mesure

### ISSUE THREAD

**Issue by gbert1** [dvoitsek/recolnat-lab#66]
La nouvelle mesure doit apparaître dans l'inspecteur.

**Comment by dvoitsek** [comment]
Si je n'ai pas le temps de faire ça pour la 0.9.1 ce sera pour la 0.9.2.

**Comment by gbert1** [comment]
J'ai l'impression que c'est central.
C'est un double feedback pour l'utilisateur : 

1/ de gestion de tâche : cet affichage lui assure que la mesure a bien été enregistrée par le système

2/ épistémologique : ça rend tangible le travail scientifique qu'il est en train de mener

**Comment by dvoitsek** [comment]
Dans ce cas il y a une chance non-négligeable qu'on ne puisse pas livrer avant la rentrée.

**Comment by gbert1** [comment]
Je ne disais pas qu'il fallait le faire maintenant :-) 
C'est juste pour dire à quel point cet inspecteur est central dans l'activité utilisateur.

**Comment by dvoitsek** [comment]
Je suis tout à fait d'accord sur son importance.

**Comment by dvoitsek** [comment]
Fait en dev
