### ISSUE TITLE
Effacer l'intitulé qd la mesure a été enregistrée

### ISSUE THREAD

**Issue by gbert1** [dvoitsek/recolnat-lab#67]
sinon on croit que l'on est toujours sur la même et on ne comprend pas que l'on peut en commencer une nouvelle

**Comment by dvoitsek** [comment]
Le dernier atelier a fait ressortir le besoin de pouvoir créer de nombreuses mesures avec un intitulé complexe ("Tige 1 / Feuille 3 / Foliole 2") qui ne serait pas pratique à retaper.

A l'heure actuelle le texte dans le popup change déjà après l'enregistrement d'un angle pour indiquer qu'on peut en commencer un nouveau.

**Comment by gbert1** [comment]
Dmitri, ce fonctionnement est totalement perturbant. 
En effet, c'est ce que l'on a tapé qui est signifiant : on croit que l'on est toujours sur la mesure précédente.
Pour toi qui connaît le fonctionnement, c'est évident mais pour moi ça ne marche pas.

Si l'utilisateur veut éviter de ressaisir un intitulé identique, il lui suffit de le mettre dans le presse-papier. De plus la plupart du temps ça oblige à effacer pour taper un intitulé différent.

**Comment by dvoitsek** [comment]
Implémenté en dev pour tous les popups.
