### ISSUE TITLE
Impossible de poser un sommet d'angle sur un chemin

### ISSUE THREAD

**Issue by gbert1** [dvoitsek/recolnat-lab#69]
Qd on est en mode mesure, on ne doit pas être en mode sélection d'item pour l'inspecteur.

**Comment by dvoitsek** [comment]
Je ne comprends pas le lien entre l'intitulé du ticket et la description. Est-ce un problème de rapporteur ou de règle ?

**Comment by gbert1** [comment]
C'est un pb des 2.
Je te le décris ci-dessous : 
il n'est pas possible de poser un point de règle ou de rapporteur sur un chemin.

(étant donné que le rapporteur fonctionne avec un pivot, on est obligé de tracer 2 chemins sécants lorsque l'on veut mesurer un angle dont le pivot n'existe pas)

**Comment by dvoitsek** [comment]
Corrigé en dev
