### ISSUE TITLE
Poignée déplacement planche

### ISSUE THREAD

**Issue by gbert1** [dvoitsek/recolnat-lab#7]
Je propose d'afficher à la place du point actuel : 

une icône avec à sa droite le texte : "Move" et en roll over le texte "Move sheet on the benchtop"

mettre le texte ds le même gris que l'icône ci-dessous

tu trouveras une icône SVG ad hoc ici : 
https://moodle2.unifr.ch/pluginfile.php/196104/mod_page/content/7/dragdrop.svg

**Comment by dvoitsek** [comment]
Ok pour l'icône et le rollover. 

Par contre tout texte va poser le problème suivant : impossible de le maintenir correctement affiché en fonction du zoom. C'est la même raison pour laquelle les titres des planches ne sont pas ajustés en fonction du zoom.

**Comment by gbert1** [comment]
Dans ce cas, en faire une image. 
Je viens de la faire en PNG : voir PJ.

Mais peut-être la veux-tu en SVG ?

<img width="58" alt="icone move" src="https://cloud.githubusercontent.com/assets/19670563/15889030/b803a9e4-2d69-11e6-913a-6b8e068d6eac.png">

**Comment by dvoitsek** [comment]
Le problème n'est pas si le texte est dans l'image ou dans un élement séparé. Le problème c'est la présence du texte. Tu pourras voir par toi-même à la prochaine mise à jour.

**Comment by dvoitsek** [comment]
Je viens de mettre à jour, je te laisse constater le résultat.

**Comment by gbert1** [comment]
Ça ne va pas.
Peux-tu me dire si avec un SVG le pb est résolu ?

**Comment by dvoitsek** [comment]
Le problème n'est pas le format d'image, mais le texte. Il ne faut pas mettre de texte.

**Comment by dvoitsek** [comment]
Ou plus, précisément, si on met des icones elles doivent être carrées et faire moins de 10 pixels. Les carrés noirs actuels font 5 pixels de côté.

**Comment by gbert1** [comment]
J'ai compris qu'il ne faut pas mettre de texte. Tu n'as pas répondu à ma question sur le format SVG.

**Comment by dvoitsek** [comment]
Dans ce cas je n'ai pas compris la question sur le format SVG. Quel problème précis veux-tu savoir si ça résout ?

**Comment by gbert1** [comment]
Je veux savoir si cela permet d'avoir une icône s'adaptant au zoom sans être ni microscopique ni g"ante, mais tjrs raccord avec la barre du haut de la planche.

**Comment by dvoitsek** [comment]
Dans ce cas ça n'a aucun rapport avec le format de l'image. La barre du haut de la planche et son contenu ne peuvent pas être indépendantes du zoom sans tomber dans le même problème d'affichage que l'icône. Donc l'icône (que ce soit en forme d'image ou de carré noir) n'est jamais raccord avec la barre.

Néanmoins l'icône sans le texte en SVG n'est pas désagréable à regarder.

**Comment by dvoitsek** [comment]
Déployé en test.
