### ISSUE TITLE
Paillasse vide à la réouverture d'un set déjà affiché par le passé

### ISSUE THREAD

**Issue by gbert1** [dvoitsek/recolnat-lab#71]
Lorsque l'on réouvre un set sur lequel on a travaillé lors d'une session précédente, alors la paillasse est vide.
Pour provoquer son affichage, il faut passer en mode agencement.

**Comment by gbert1** [comment]
Voir #74

**Comment by dvoitsek** [comment]
Corrigé en dev et déployé en test.
