### ISSUE TITLE
L'ajout d'une annotation empêche l'affichage dans l'inspecteur de ce sur quoi on l'a posé

### ISSUE THREAD

**Issue by gbert1** [dvoitsek/recolnat-lab#72]
J'ai posé une annotation sur un chemin puis sur un angle.
À chaque fois, les détails de l'objet annoté (longueur, heure, auteur) ne s'affichent plus dans l'inspecteur quand on clique sur l'objet.
Comme si le fait d'annoter bloquait l'affichage dans l'inspecteur.

**Comment by dvoitsek** [comment]
Corrigé en dev.
