### ISSUE TITLE
Le bouton "Ouvrir le set sélectionné" est bogué

### ISSUE THREAD

**Issue by gbert1** [dvoitsek/recolnat-lab#74]
Qd on clique dessus, on retourne bien sur la paillasse mais sans que le set qui y est soit remplacé par celui que l'on avait sélectionné dans le SM et dont on avait demandé l'ouverture.

**Comment by gbert1** [comment]
En fait, c'est le même bug que #71 : si l'on clique sur Agencement ça provoque l'affichage.
Et idem si on essaie d'afficher un nouveau set alors qu'il y en a déjà un sur la paillasse.

**Comment by dvoitsek** [comment]
Corrigé en dev et déployé en test.
