### ISSUE TITLE
ce doit être un pb exif ds l'image EY6339

### ISSUE THREAD

**Issue by gbert1** [dvoitsek/recolnat-lab#75]
Sur une des images :
Xyelidae / Xyelatana lugdunensis / Berland, 1943 / EY6339

il y a un échelle affichée "1 mm" 
qd je la mesure avec la règle du collaboratoire et donc ses données exif elle affiche 156mm

<img width="1171" alt="capture d ecran 2016-07-20 15 15 22" src="https://cloud.githubusercontent.com/assets/19670563/16987592/5d8d746e-4e8d-11e6-9c36-56a1088beb0b.png">

**Comment by dvoitsek** [comment]
Les données EXIF me disent que le DPI est de 96. On ne numérisait pas en 300 ?

**Comment by gbert1** [comment]
Ce ne sont pas des images numérisées dans ce cadre.
J'ai mis dans chili, je pense que Julien va envoyer ça à la personne concernée par la collection.

**Comment by dvoitsek** [comment]
Vu qu'on a un outil d'étalonnage ce problème n'est plus du ressort du Collaboratoire. Du coup je ferme le ticket.
