### ISSUE TITLE
POI ne fonctionne pas

### ISSUE THREAD

**Issue by gbert1** [dvoitsek/recolnat-lab#78]
Je viens de retester sur 2 sets différents. Je n'ai tjrs pas de panonceau qui apparaît qd je clique dans l'image.

**Comment by dvoitsek** [comment]
Je ne peux pas reproduire ce problème : le panneau apparaît quand je clique sur une image. As-tu essayé de vider le cache de ton navigateur ?

**Comment by gbert1** [comment]
Moi aussi, le panneau apparaît. C'est après que rien ne se passe : voir copie écran (le curseur disparaît pdt la copie écran).

Oui, j'ai vidé mon cache.

<img width="1280" alt="capture d ecran 2016-07-20 16 41 14" src="https://cloud.githubusercontent.com/assets/19670563/16990614/e576bca4-4e98-11e6-8b09-5ed7bc21fd1a.png">

**Comment by dvoitsek** [comment]
Chez moi, sur la version de test, le panneau apparaît, reste en place pendant la copie écran et est bien sauvegardé au moment de la validation et apparaît bien après la mise à jour post-enregistrement.

As-tu essayé de redémarrer ta machine ?

**Comment by gbert1** [comment]
Mais arrives-tu à poser des POI ?

**Comment by dvoitsek** [comment]
Le processus décrit là-haut est ce que j'appelle "poser des PoI" : oui j'arrive à les poser.

**Comment by gbert1** [comment]
Avec clic gauche souris ?

**Comment by dvoitsek** [comment]
Oui.

**Comment by gbert1** [comment]
marche pas sur mac

**Comment by dvoitsek** [comment]
As-tu essayé avec un autre mac ?

Pour info rien n'a changé au niveau du code qui traite le signal "clic gauche", donc si ça marchait avant il n'y a aucune raison que ça ne marche plus.

**Comment by gbert1** [comment]
mystère
met en ligne, je dois partir
je retesterai demain matin

**Comment by dvoitsek** [comment]
Duplicata de #85, désormais corrigé.
