### ISSUE TITLE
Set avec 1 seule image non centré à l'ouverture

### ISSUE THREAD

**Issue by gbert1** [dvoitsek/recolnat-lab#79]
J'ai créé un set avec une seule image : P02211896

Qd je l'ouvre sur la paillasse avec le placement automatique mosaïque : 
l'image ne s'affiche pas au centre de la paillasse mais en haut à gauche et en petit
alors qu'elle devrait être centrée et occuper toute la paillasse

**Comment by dvoitsek** [comment]
Aucun problème constaté avec 1 image dans la version actuelle. Probablement corrigé en cours de route lors du passage en websocket.
