### ISSUE TITLE
Fenêtre CAS non fermée --> utilisable seulement par nous

### ISSUE THREAD

**Issue by gbert1** [dvoitsek/recolnat-lab#82]
La fenêtre CAS ne se ferme pas une fois l'authentification faite. Il faut coller l'URL à la place dans la barre d'adresse pour réussir à accéder au collaboratoire. Cela rend le logiciel quasiment utilisable que par toi et moi :-)

**Comment by dvoitsek** [comment]
Oui, c'était ce que je t'avais indiqué dans le mail il y a 2 semaines en disant que c'était temporaire :-)

**Comment by gbert1** [comment]
Je sais, oui :-) C'était pour que tu t'en souviennes... bon courage pour ta
reprise.

2016-09-19 10:37 GMT+02:00 dvoitsek notifications@github.com:
