### ISSUE TITLE
Pas de statut de chargement en cours pdt le download pour le zoom

### ISSUE THREAD

**Issue by gbert1** [dvoitsek/recolnat-lab#83]
Suite à un zoom 1:1, il n'y a pas d'affichage "Chargement en cours" pendant que le logiciel télécharge l'image zoomée en HR.

**Comment by dvoitsek** [comment]
Parfois l'image devient disponible avant que le message n'ait le temps de s'afficher.

C'est un problème de message manquant ou d'image qui ne se télécharge pas au final ?

**Comment by dvoitsek** [comment]
Bug dans le centrage du zoom 1:1 désormais corrigé.
