### ISSUE TITLE
Points remarquables non visibles pendant et après leur pose

### ISSUE THREAD

**Issue by gbert1** [dvoitsek/recolnat-lab#85]
La pancarte des points remarquables n'est visible ni pendant, ni après la pose. Alors que manifestement la fonctionnalité "fonctionne" et que le point est bien posé puis enregistré.

**Comment by dvoitsek** [comment]
Ok, j'essaie de comprendre.

Quand l'outil POI est actif si tu cliques sur une image tu n'as pas le marqueur qui apparait. Par contre si tu valides, le POI est bien affiché après rechargement. C'est bien ça ?

**Comment by gbert1** [comment]
Non, il n'est pas non plus affiché après !

**Comment by dvoitsek** [comment]
Dans ce cas comment tu sais qu'il est bien enregistré ?

**Comment by dvoitsek** [comment]
Ok, finalement j'ai trouvé la source du problème. FF n'interprète pas les SVG de la même manière que Chrome. C'est résolu et mis en test.

**Comment by gbert1** [comment]
parce que la petite boîte d'enregistrement fonctionne de façon correcte

2016-09-21 10:57 GMT+02:00 dvoitsek notifications@github.com:

**Comment by gbert1** [comment]
cool, je v tester
