### ISSUE TITLE
Blocages Firefox

### ISSUE THREAD

**Issue by gbert1** [dvoitsek/recolnat-lab#86]
Quand je passe en 1:1 puis que je commence à déplacer le carré rouge de visualisation sur la planche zoomée, cela déclenche un chargement qui ne se termine jamais. 
Le ventilateur de la machine se met à tourner indiquant une activité très forte.
Je suis obligé de killer FF. Je suis en ADSL.

Cela se produit sur 2 sets totalement différents.

<img width="1280" alt="capture d ecran 2016-09-20 14 44 44" src="https://cloud.githubusercontent.com/assets/19670563/18670830/f2fe3260-7f41-11e6-8ca2-b7c56b586f45.png">

<img width="1280" alt="capture d ecran 2016-09-20 14 49 15" src="https://cloud.githubusercontent.com/assets/19670563/18670850/0660b4ea-7f42-11e6-95e9-252628d6f1e0.png">

**Comment by dvoitsek** [comment]
Je n'arrive pas à reproduire ce bug. 

La nature de la connexion n'a pas d'importance, il n'y a pas d'échanges réseau associés à ce geste.

Peux-tu me donner les spécifications de ta machine ? (CPU, RAM, n° version FF, n° version OS)

**Comment by gbert1** [comment]
Mac, OS X Maverick, 8Go, Firefox version 48.0.1
Je pensais au réseau parce que (tu peux le voir sur la 2ième image) il y a un chargement en cours.
C'est pendant que je bouge alors qu'il y a chargement.

**Comment by dvoitsek** [comment]
Visiblement un problème avec certains plugins FF et/ou l'accéleration graphique sous certaines versions de Mac OS.
