### ISSUE TITLE
Création set ne se termine jamais

### ISSUE THREAD

**Issue by gbert1** [dvoitsek/recolnat-lab#87]
La création du set ne se termine jamais.
Il charge le double de spécimens : 
1er test : 48 pour 24 sélectionnés dans Explore
2ième test : 18 pour 9 sélectionnés dans Explore

Les planches st bien affichées à gauche. Les images st affichées à droite. La roue continue à tourner. Voir copie écran.

<img width="960" alt="capture d ecran 2016-09-27 17 26 24" src="https://cloud.githubusercontent.com/assets/19670563/18880417/12048682-84d8-11e6-9666-1043578040b5.png">

**Comment by dvoitsek** [comment]
J'ai finalement réussi à reproduire et corriger : ça n'arrivait que dans la première colonne.
