### ISSUE TITLE
La suppression de set ne fonctionne pas

### ISSUE THREAD

**Issue by gbert1** [dvoitsek/recolnat-lab#88]
Qd on clique sur l'icône rouge pour retirer le set de la racine, puis qu'on valide, il ne se passe rien.

<img width="394" alt="capture d ecran 2016-09-28 11 49 08" src="https://cloud.githubusercontent.com/assets/19670563/18908859/97e50d14-8571-11e6-8a99-e15b70c3b284.png">

**Comment by dvoitsek** [comment]
Ca tombe bien, je viens tout juste de voir et corriger ça ;-)
