### ISSUE TITLE
Nouvelle(s) planche(s) non affichée(s) qd set ouvert sur paillasse

### ISSUE THREAD

**Issue by gbert1** [dvoitsek/recolnat-lab#9]
Qd je travaille sur la paillasse et que je retourne dans le SM ajouter une planche au set, elle doit au retour : 
1/ être ajoutée sur la paillasse, ceci à droite de la dernière planche
2/ l'affichage centré sur elle
3/ avec le même facteur de zoom

**Comment by dvoitsek** [comment]
Je pense que c'est mieux si l'utilisateur peut rajouter une planche au set sans passer par le SM. Est-ce que tu peux proposer une ergonomie pour avoir l'option de rajouter de nouvelles planches directement depuis la paillasse ?

**Comment by dvoitsek** [comment]
Résolu dans la version de dev. Les nouvelles planches ajoutées dans le SM arriveront dans la Inbox. Un bouton en bas à droite dans la paillasse permet de rajouter des planches sans passer par le SM qui sont immédiatement positionnées dans la vue..
