### ISSUE TITLE
Fantôme sur la paillasse du bouton supprimer du gestionnaire de set

### ISSUE THREAD

**Issue by gbert1** [dvoitsek/recolnat-lab#90]
Si je clique bouton droit sur un set dans le gestionnaire de set puis que je sélectionne "supprimer" (icône rouge) alors ensuite quand je vais sur la paillasse, cette icône rouge est posée sur la paillasse.

Je n'ai pas fait l'essai sans cliquer sur "Supprimer", peut-être les icônes du bouton droit apparaissent-elles sur la paillasse dans tous les cas.

**Comment by dvoitsek** [comment]
Corrigé.
