### ISSUE TITLE
Enregistrements ne fonctionnent plus

### ISSUE THREAD

**Issue by gbert1** [dvoitsek/recolnat-lab#91]
Les enregistrements des mesures de longueur et d'angle comme celles des points ne fonctionnent plus. Il ne se passe rien qd on valide? Il n'apparaît pas la mesure en rouge sur la paillasse. Ni rien à droite.

**Comment by dvoitsek** [comment]
Le trait rouge est masqué par les "traits de construction" de l'outil. Si tu désactives l'outil tu verras le trait rouge. C'est le même fonctionnement que pour la VM.

Pour la mesure d'angle on peut envisager à l'avenir de la changer pour que ça supprime les traits de construction après enregistrement.

Pour la règle c'est inhérent au fait de pouvoir poser plusieurs mesures et de pouvoir repositionner les points de l'outil après enregistrement. Si on enlève l'une ou l'autre de ces fonctionnalités on pourra règles le problème d'affichage.

Le fait que rien ne change à droite (je suppose que tu veux parler de l'inspecteur) est pareil que dans la VM. Je suis tout à fait d'accord que c'est pas bien et ça fait partie des choses à refaire au niveau de l'inspecteur dont on avait discuté avant.

**Comment by dvoitsek** [comment]
Je ferme le ticket. Pour les changements d'ergonomie des outils on verra quand on y sera.
