### ISSUE TITLE
Clic sur planche dans paillasse ne provoque pas toujours màj minivue

### ISSUE THREAD

**Issue by gbert1** [dvoitsek/recolnat-lab#93]
sélectionner une planche sur la paillasse (clic sur elle pour raison qq) ne provoque pas toujours la mise à jour de la minivue et du barillet

**Comment by dvoitsek** [comment]
Pas reproductible dans la version actuelle, donc probablement corrigé. Faire attention à différencier cliquer sur un objet de la paillasse et faire glisser la vue de la paillasse. Dans ce dernier cas il n'y a pas de sélection faite.
