### ISSUE TITLE
format date heure

### ISSUE THREAD

**Issue by gbert1** [dvoitsek/recolnat-lab#95]
Je propose et on peut en discuter si besoin de remplacer : 

Création : 27/06/2016 à 17:46:09

par

Création : lundi 27/06/16 à 17:46

**Comment by dvoitsek** [comment]
Ca va pas prendre plus de temps que ce que je pense que tu penses : problèmes d'internationalisation du jour.

Tu confirmes vouloir ce changement en priorité ?

**Comment by gbert1** [comment]
ce n'est pas prioritaire
enlève slt les secondes

**Comment by dvoitsek** [comment]
Finalement le jour était plus simple que je ne pensais.
