### ISSUE TITLE
Fenêtre d'annotation

### ISSUE THREAD

**Issue by gbert1** [dvoitsek/recolnat-lab#97]
L'ennui de la fenêtre de l'annotation est qu'elle cache ce que l'on veut annoter.

Je propose 2 solutions : 

a/ un petit volet qui s'ouvre en bas de "Propriétés" (ce serait ma préférence mais il risque de faire scroller la sidebar de droite)

b/ une fenêtre plus petite, déplaçable à la souris et de ne pas jouer sur l'opacité de l'écran

**Comment by dvoitsek** [comment]
Je peux proposer a/ mais à la place de l'ouvrir dans la palette PP ça s'ouvre en popup par-dessus, ce qui évite les problèmes de scrolling et d'occultation de l'écran.

**Comment by gbert1** [comment]
il ne faut pas non plus masquer les infos de pp

2016-10-06 16:15 GMT+02:00 dvoitsek notifications@github.com:

**Comment by dvoitsek** [comment]
Est-ce que ça te convient si je le mets dans le même style que le popup des outils (mesure, annotation, etc) ?

**Comment by gbert1** [comment]
je ne vois pas ce que tu veux dire

2016-10-07 16:03 GMT+02:00 dvoitsek notifications@github.com:

**Comment by dvoitsek** [comment]
Quand tu sélectionnes un outil (par exemple la règle), tu as une fenêtre qui apparait sur la paillasse avec les instructions à suivre et le texte à entrer. Ce que je propose c'est de mettre la fenêtre "nouvelle annotation" à cet endroit, avec la même apparence.

**Comment by gbert1** [comment]
c'est bizarre cognitivement

en effet pour les outils c'est logique, on travaille alors sur la paillasse

alors que pour saisir un "Commentaire", on devrait être à proximité de la
boîte "Propriétés"

**Comment by dvoitsek** [comment]
Fait selon option a.
